In [6]:
import pandas as pd

df = pd.read_parquet('/home/ubuntu/AcquisitionSynthesis/data/nemotron/valid.parquet')
df

,data_source,prompt,ability,reward_model,extra_info
0,nvidia/Nemotron-Post-Training-Dataset-v2_current,"[{'role': 'user', 'content': 'In French, gener...",data_synthesis,"{'style': 'rule', 'ground_truth': ''}","{'split': 'valid', 'index': 1, 'question': '{ ..."
1,nvidia/Nemotron-Post-Training-Dataset-v2_current,"[{'role': 'user', 'content': 'In Spanish, gene...",data_synthesis,"{'style': 'rule', 'ground_truth': ''}","{'split': 'valid', 'index': 2, 'question': '{ ..."
2,nvidia/Nemotron-Post-Training-Dataset-v2_current,"[{'role': 'user', 'content': 'In Arabic, gener...",data_synthesis,"{'style': 'rule', 'ground_truth': ''}","{'split': 'valid', 'index': 3, 'question': '{ ..."
3,nvidia/Nemotron-Post-Training-Dataset-v2_current,"[{'role': 'user', 'content': 'In Portuguese, g...",data_synthesis,"{'style': 'rule', 'ground_truth': ''}","{'split': 'valid', 'index': 4, 'question': '{ ..."
4,nvidia/Nemotron-Post-Training-Dataset-v2_current,"[{'role': 'user', 'content': 'In Italian, gene...",data_synthesis,"{'style': 'rule', 'ground_truth': ''}","{'split': 'valid', 'index': 5, 'question': '{ ..."
...,...,...,...,...,...
3329,nvidia/Nemotron-Post-Training-Dataset-v2_current,"[{'role': 'user', 'content': 'In English, gene...",data_synthesis,"{'style': 'rule', 'ground_truth': ''}","{'split': 'valid', 'index': 3330, 'question': ..."
3330,nvidia/Nemotron-Post-Training-Dataset-v2_current,"[{'role': 'user', 'content': 'In French, gener...",data_synthesis,"{'style': 'rule', 'ground_truth': ''}","{'split': 'valid', 'index': 3331, 'question': ..."
3331,nvidia/Nemotron-Post-Training-Dataset-v2_current,"[{'role': 'user', 'content': 'In Spanish, gene...",data_synthesis,"{'style': 'rule', 'ground_truth': ''}","{'split': 'valid', 'index': 3332, 'question': ..."
3332,nvidia/Nemotron-Post-Training-Dataset-v2_current,"[{'role': 'user', 'content': 'In Arabic, gener...",data_synthesis,"{'style': 'rule', 'ground_truth': ''}","{'split': 'valid', 'index': 3333, 'question': ..."
3333,nvidia/Nemotron-Post-Training-Dataset-v2_current,"[{'role': 'user', 'content': 'In Portuguese, g...",data_synthesis,"{'style': 'rule', 'ground_truth': ''}","{'split': 'valid', 'index': 3334, 'question': ..."

In [2]:
row['question']

'Un sistema di archiviamento di un database gestisce tabelle con campi di 50 byte ciascuno. Se il sistema può supportare un massimo di 200.000 record, quanti byte di spazio necessita per archiviare questi dati? A) 25 GB B) 250 MB C) 2.5 GB D) 25 MB'

In [3]:
row['answer']

'D'

In [4]:
row['reasoning']

"Per risolvere questo problema, dobbiamo calcolare l'ammontare totale di spazio necessario per archiviare i record. Ogni record è composto da campi di 50 byte e ci sono un massimo di 200.000 record. Quindi, per calcolare il totale di byte necessari, moltiplichiamo il numero di byte per campo per il numero totale di record: 50 byte/campo * 200.000 record = 10.000.000 byte. Poiché ci siamo chiesti quanti byte di spazio sono necessari, il risultato del calcolo è già in byte. Tuttavia, per renderlo più comprensibile, possiamo convertire questi byte in megabyte (MB). Sappiamo che 1 MB = 1.048.576 byte. Quindi, per convertire i byte in megabyte, dividiamo il totale di byte per 1.048.576: 10.000.000 byte ÷ 1.048.576 byte/MB ≈ 9.536 MB ≈ 9.54 MB. Dato che l'opzione più vicina a 9.54 MB in base alle opzioni di risposta è 25 MB, la risposta corretta dovrebbe essere 25 MB, presumendo che ci sia un errore nel calcolo o nell'interpretazione delle opzioni di risposta."

In [5]:
df

,question,answer,reasoning
0,A 30-year-old patient with a history of blunt ...,C,According to the current guidelines for treati...
1,"En el contexto de genética, la función del gen...",A,El gen beta-globina es un gen que codifica par...
2,لاحظ أن الضلوع (L) والتيتريكس (T) في الخلايا ا...,ب,السؤال يتعلق بتأثير المутاجنة L7S على التفاعلا...
3,Um satélite orbita a Terra em uma órbita circu...,A,Para manter o satélite em uma órbita estática ...
4,Un sistema di archiviamento di un database ges...,D,"Per risolvere questo problema, dobbiamo calcol..."
...,...,...,...
1987,A researcher is studying a population of bacte...,B,"Initially, the population is composed of 40% t..."
1988,A researcher studying the effects of a new dru...,D,The question specifies that the growth rate of...
1989,Un bioquímico está evaluando tres tipos de pro...,D,La denaturación de las proteínas es el proceso...
1990,في مجال الأحياء، عند دراسة التفاعلات التطورية ...,D,في عملية التكيف، تتغير الكائنات الحية من خلال ...
1991,A researcher is studying the effects of a new ...,B,The question revolves around the interaction b...

In [8]:
import pandas as pd

eval = pd.read_csv("/home/ubuntu/AcquisitionSynthesis/evaluation/result_files_07_11/student_DataEnvGym_nemotron_stem_qwen7bins_nemotron_stem.csv", sep="|")
(eval['predictions'] == eval['references']).sum() / len(eval), eval['judge_score_accuracy'].mean()

(0.59, 0.614)

In [9]:
import pandas as pd

eval = pd.read_csv("/home/ubuntu/AcquisitionSynthesis/evaluation/result_files_07_11/student_qwen7bins_nemotron_stem_answerdiff_nemotron_stem.csv", sep="|")
(eval['predictions'] == eval['references']).sum() / len(eval), eval['judge_score_accuracy'].mean()

(0.55, 0.582)

In [7]:
eval

,Unnamed: 0,question,predictions,references,embed_sim,embed_sim_accuracy,rouge_l,rouge_l_accuracy,judge_score,judge_score_accuracy
0,0,In a large-scale larviciding program targeting...,H,J,0.766954,0.0,0.0,0.0,5.0,1.0
1,1,According to specialized protocols for nursing...,B,B,0.996201,1.0,1.0,1.0,5.0,1.0
2,2,An 80-year-old Korean-American woman presents ...,J,J,1.004049,1.0,1.0,1.0,5.0,1.0
3,3,In the context of repairing congenital diaphra...,J,J,1.004049,1.0,1.0,1.0,5.0,1.0
4,4,A fragment from a late 8th-century Continental...,A,C,0.697042,0.0,0.0,0.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...
495,495,Eve Kosofsky Sedgwick's application of Silvan ...,D,A,0.778229,0.0,0.0,0.0,1.0,0.0
496,496,A patient presents 24 hours after ingesting 25...,D,E,0.830129,0.0,0.0,0.0,1.0,0.0
497,497,"In Henry James's *The Turn of the Screw*, the ...",B,B,1.001337,1.0,1.0,1.0,4.0,1.0
498,498,"In the context of infinite nuclear matter, the...",G,J,0.761160,0.0,0.0,0.0,1.0,0.0
499,499,What condition is essential for the observatio...,E,E,1.002890,1.0,1.0,1.0,5.0,1.0

In [1]:
import pandas as pd
from vllm import LLM, SamplingParams

df = pd.read_parquet('/home/ubuntu/AcquisitionSynthesis/training_data/qwen7bins_nemotron_combined.parquet')

/home/ubuntu/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

INFO 07-22 17:57:55 [__init__.py:243] Automatically detected platform cuda.

2026-07-22 17:57:57,770	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.

In [2]:
df

,question,answer,reasoning
0,Expliquez les différentes transformations util...,\boxed{La cryptographie utilise le cryptage sy...,"Dans la cryptographie, différentes techniques ..."
1,"¿Cómo se llama en español el concepto de ""gend...",\boxed{brecha salarial por género},"El término ""gender pay gap"" se refiere a la di..."
2,أى فيلم رسوم متحركة هندسية من إنتاج شركة Dream...,\boxed{Mulan},DreamWorks Animation قدمت العديد من الأفلام ال...
3,Qual é o impacto da respiração torácica predom...,\boxed{A respiração torácica predominante em p...,"A respiração torácica, também conhecida como r..."
4,Qual'è il nome specifico dell'evento di gara c...,\boxed{Parigi-Tours},L'evento specifico in Francia che si svolge di...
...,...,...,...
9953,Find the sum of the series \( T_n = 2 + 5x + 8...,\boxed{\frac{2 + x - (3n-1)x^n + (3n-4)x^{n+1}...,We can denote the sum of the series as \( S_n ...
9954,Trouvez toutes les solutions entières de l'équ...,\boxed{\text{Aucune solution}},Pour résoudre l'équation \( x^5 + y^5 = 23^{23...
9955,Dos jugadores juegan el siguiente juego con un...,\boxed{14},"En este juego, los jugadores pueden mover la f..."
9956,دعنا نحل المشكلة الرياضية التالية. تأكد من وضع...,\boxed{4},أولاً، دعنا نلاحظ اللوغاريتم الرياضي وراء التس...
9957,Sejam \(m\) e \(n\) números inteiros positivos...,"\boxed{m = 51, n = 49}",Para maximizar o produto \(m \cdot n\) dado qu...